platform :ios, '13.0'

# Safely load flutter_export_environment if it exists
flutter_export_environment = File.expand_path('../Flutter/flutter_export_environment', __FILE__)
load(flutter_export_environment) if File.exist?(flutter_export_environment)

require File.expand_path('../Flutter/podhelper.rb', __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
